import { useState, useCallback } from "react";
import Head from "next/head";
import Image from "next/image";
import axios from "axios";

import "@itcenteratunihelsinki/huds-lib/dist/fonts/fonts.css";
import "@itcenteratunihelsinki/huds-lib/dist/huds-lib/huds-lib.css";
import styles from "../styles/Home.module.scss";
import { useLocalizationContext } from "../components/LocalizationContext";
import WeekCalendar from "../components/WeekCalendar";
import OrganisationSelector from "../components/OrganisationSelector";

export async function getServerSideProps(context) {
  const res = await axios.get(
    "http://127.0.0.1:3001/api/events-by-organisation"
  );
  if (res.data.status !== "ok") {
    return {
      props: {
        events: {
          "organisations-by-id": {},
          events: {},
        },
      },
    };
  }

  return {
    props: {
      events: res.data.data,
    },
  };
}

/**
 * @param {{ events: import("../api").Data }} props
 */
function Lectures({ events }) {
  const { l } = useLocalizationContext();

  const sortedOrganizations = Object.values(events["organisations-by-id"]).sort(
    (a, b) => l(a.name).localeCompare(l(b.name))
  );

  const [selectedOrganisations, setSelectedOrganisations] = useState([
    // sortedOrganizations[0].id,
    // pre-select CS BSc and MSc
    "hy-org-116716376",
    "hy-org-116738259",
  ]);

  const handleOrganisationChange = useCallback(
    (newValues) => {
      setSelectedOrganisations(newValues.map((kv) => kv.value));
    },
    [setSelectedOrganisations]
  );

  return (
    <div>
      <div>
        <OrganisationSelector
          className={styles.org_selector}
          options={sortedOrganizations.map((org) => ({
            value: org.id,
            label: l(org.name),
          }))}
          value={selectedOrganisations}
          onChange={handleOrganisationChange}
        />
      </div>
      <div style={{ marginTop: "1rem" }}>
        <WeekCalendar
          events={selectedOrganisations.flatMap(
            (id) => events.events[id] || []
          )}
        />
      </div>
    </div>
  );
}

/**
 * @param {{ events: import("../api").Data }} props
 */
export default function Home({ events }) {
  const { langs, setLang } = useLocalizationContext();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Header /> */}

      <main className={styles.main}>
        <h1 className={styles.title}>
          Luentolista <span className={styles.title__emphasis}>Exactum</span>
        </h1>

        <div className={styles.description}>
          <div>
            Lang:{" "}
            <select
              onChange={(e) => {
                setLang(e.currentTarget.value);
              }}
            >
              {langs.map((lang) => (
                <option key={lang} value={lang}>
                  {lang}
                </option>
              ))}
            </select>
          </div>
          <Lectures events={events} />
        </div>
      </main>

      <footer className={styles.footer}>footer</footer>
    </div>
  );
}
